# **Naive Bayes**

A Naive Bayes classifier is a probabilistic machine learning model that’s used for classification task. The crux of the classifier is based on the Bayes theorem.

**What will you learn?**

1. **Bayes Theorem**: An introduction
2. **Naive Assumption**: Calculation of probability for Naive Bayes Algo.
3. **Implementation with Discrete Data**: Theory and code structure.
4. **Laplace Correction**: Handling zero probabilities.
5. **Self Implementation**: Code for Categorical Input.
6. **Scikit Learn Implementation**: GaussianNB, MultinomialNB, CategoricalNB and BernoulliNB.
7. **Applications of Naive Bayes**: When to use which type of Naive algorithm.
8. **Tips to Improve your Model**: How to process data
9. **Advantages and Disadvantages**: Pros and cons of using naive bayes classifier

## **Introduction to Bayes Theorem**

Bayes Theorem defines probability of an event based on the prior knowledge of factors that might be related to an event.

$$ P(A\;|\;B) = \frac{P(B \;|\;A) \; * P(A)}{P(B)} $$

where $A$ and $B$ are events and $P(B) \neq 0$

Here, a few points to note are :

$\qquad P(A\;|\;B)$ is a conditional probability: the likelihood of event $A$ occuring given that event $B$ has occurred.

$\qquad P(B\;|\;A)$ is also a conditional probability: the likelihood of event B occuring given that event $A$ has occurred.

$\qquad P(A)$ and $P(B)$ are the probabilities of observing A and B independently of each other.



### **How Naive Bayes Works?**

Let’s understand it by using an example. Below we have a training data set of weather and corresponding target variable ‘Play’ (suggesting possibilities of playing). Now, we need to classify whether players will play or not based on weather. Let’s follow the following steps to perform it.

**Step 1:** Convert the data set into a frequency table

**Step 2:** Create a Likelihood table by finding the probabilities like Overcast probability = 0.29 and probability of playing = 0.64.

<img src = "https://files.codingninjas.in/bayes_41-7363.png">
(In this image, a blank cell represents '0')

**Step 3:** Now, use Naive Bayesian equation to calculate the posterior probability for each class. The class with the highest posterior probability is the outcome of prediction.

**Problem:** Players will play if weather is sunny. Is this statement is correct?

We can solve it using above discussed method of posterior probability.

$$P(Yes \;| \;Sunny) = \frac{P( Sunny\; | \;Yes) * P(Yes)}{P (Sunny)}$$

Here we have $P (Sunny |Yes) = 3/9 = 0.33$, $P(Sunny) = 5/14 = 0.36$, $P( Yes)= 9/14 = 0.64$

Now, 

$$P (Yes \;|\; Sunny) = \frac{0.33 * 0.64} { 0.36 }= 0.59$$
which is a high probability.

Naive Bayes uses a similar method to predict the probability of different class based on various attributes. This algorithm is mostly used in text classification and with problems having multiple classes.

Now, basically for a data point $x_i$, we have to predict the class that the current output $y$ belongs to. Assume, there are total $j$ number of classes for output.
Then,

$P(y=c_1 \;| \; x=x_i)$ : tells us that for given input $x_i$ what is the probability that $y$ is $c_1$.

$P(y=c_2 \;| \; x=x_i)$ : tells us that for given input $x_i$ what is the probability that $y$ is $c_2$.

and so on till $c_j$.


Out of all these probabilities calculations, $y$ belongs to that particular class which has maximum probability.

We will be using Bayes theorem for doing these probability calculations. The formula is given as:

$$P(y = c_j \; | \; x = x_i) = \frac{P(x = x_i \; | \; y = c_j) * P(y = c_j)}{P(x = x_i)} $$

This gives us the probability that the output belongs to $j^{th}$ class for the current values of data point $(x_i)$.


Since for all the classes 1, 2,..., j the denominator will have the same value, so we can ignore this while doing comparison (ultimately, we have to find the max). Hence, we obtain the given formula to calculate probabilities.

$$P'(y = c_j \; | \; x = x_i) = P(x = x_i \; | \; y = c_j) * P(y = c_j) $$

## **Naive Assumption**

The estimate for probability $P(y=c_j)$, can be done directly from the number of training points. <br/>
Suppose there are 100 training points and 3 output classes, 10 belong to class $C_1$, 30 belong to class $C_2$ and remaining 60 belong to class $C_3$. <br/>
The estimate values of class probabilities will be: <br/>
$P(y = C_1) = 10/100 = 0.1$ <br/>
$P(y = C_2) = 30/100 = 0.3$ <br/>
$P(y = C_3) = 60/100 = 0.6$ <br/>

To make the probability estimate for $P(x=x_i \; | \; y=c_j)$, naive bayes classification algorithm assumes <b>all the features to be independent</b>. 

So, we can calculate this by individually multiplying the probabilities obtained for all these features (assuming features to be independent), for the output of $j^{th}$ class.

$$P(x=x_i|y=c_j) = P(x=x_i^1 \; | \; y=c_j) * P(x=x_i^2 \; | \; y=c_j) * .... * P(x=x_i^n \; | \; y=c_j)$$

Here, $x_i^1$ denotes the value of 1st feature of $i^{th}$ data point and $x=x_i^n$ denotes the value $n^{th}$ feature of the $i^{th}$ data point.


After taking up the naive assumption, we can easily calculate the individual probabilites and then by simply multiplying the result calculate the final probability $P'$.

$$ P'(y = c_j \; | \; x = x_i) = \prod_k P(x = x_i^k \; | \; y = c_j) * P(y = c_j) $$

Finding the second term in the above formula is pretty straight forward, we shall simply divide the total training data belonging to class $c_j$, with total training data. Let's have a look at the first term.

## **Implementation with Discrete Data**

Now, let's see how we can find $P(x = x_i^k \; | \; y = c_j)$ for any one class.

Let's assume our selected class to be $c$, and the value of the input feature to be $x^j$, so the probability $P(x = x^j \; | \; y = c)$ is given by

$$ P(x = x^j \; | \; y = c) = \frac{Count \; of \; Training \; Data(x = x^j \; and \; y = c)}{Count \; of \; Training \; Data(y = c)}$$


Let's look at the previous example.

<img src = "https://files.codingninjas.in/bayes_41-7363.png">

Here, let's find the probability $P(x = Sunny \; | \; y = No)$

$$P(x = Sunny \; | \; y = No) = \frac{Count \; of \; Training \; Data(x = Sunny \; and \; y = c)}{Count \; of \; Training \; Data(y = No)}$$

$$= \frac{2}{5}$$

The above example considers only one feature for our input. To maintain computations for multi featured input, we shall use dictionaries while we write the code. Let us look at the dictionary structure.

We will implement a multi level dictionary. At the first level, we will store the classes $(c_1, c_2, c_3, ...., c_j)$ as keys, to which the data belongs to.

For each class key we will store another dictionary (second level), where the keys will be the features, ($x_j^1, x_j^2, x_j^3, ...., x_j^n$), where n is the number of features.

For each feature, we will store another dictionary (third level), where the keys will be all the possible values that feature can take. The keys of this dictionary will store the corresponding count.

**Note:** Apart from storing the feature dictionaries, the top level dictionary of each class will store one extra key, where the value would be the frequency  of occurance (total count) of that particular class.

Below is the diagramatic structue of the same.

<img src = "https://files.codingninjas.in/dict-7460.jpg" width = "650">

where $c_1, c_2, ...., c_j$ represent the classes, $x^1, x^2, x^3...., x^n$ represent the features and $l_1, l_2, l_3, ...., l_i$ represent the possible labels of each feature.



## **Laplace Correction**

Let’s consider the following situation: you’ve trained a Naive Bayes algorithm to differentiate between spam and not spam mails. What happens if the word “Casino” doesn’t show up in your training data set, but appears in a test sample?

Well, your algorithm has never seen it before, so it sets the probability that <b>"Casino" appears in a spam document</b> to <b>0</b>; So every time this word appears in the test data , you will try hard (it has P = 0) to mark it as not spam just because you have not seen that word in the spam part of training data.This will make the model very less efficient and thus we want to minimise it. We want to keep in mind the possibility of any word we have not seen (or for that matter seen in the not-spam part of training data), may have a above-zero probability of being a word used in spam mails. The same is true for each word to be a part of not-spam mails. 

To avoid such issues with unseen values for features, as well as to combat overfitting to the data set, we pretend as if we’ve seen each word 1 (or k, if you’re smoothing by k) time more than we’ve actually seen it, and adjust the denominator of our frequency divisions by the size of the overall vocabulary to account for the “pretence”, which actually works well in practice.

If you take smoothing factor k equal to 1, it becomes Laplace correction.
The equations below show Laplace correction for the example taken.

Without correction : 

$$ P(w_i \; | \; c_j) = \frac{count(w_i, c_j)}{\sum_w count(w, c_j)}$$

This is the fraction of times the word $w_i$ appears among all words in documents of topic $c_j$.

With correction :

$$ P(w_i \; | \; c) = \frac{count(w_i, c_j) + 1}{(\sum_w count(w, c_j)) + |V|} $$

where $|V|$ is the number of all possible words in mails with topic $c_j$.

## **Self Implementation of Naive Bayes**

We will work with the Iris Dataset for this example. It is a continuous data, we shall convert it into categorigal(discrete) data.

In [ ]:
import numpy as np

In [ ]:
# This function creates the dictionary as discussed in implementation theory.
def fit(X_train, Y_train):
    result = {}
    class_values = set(Y_train)
    for current_class in class_values:
        result[current_class] = {}
        result["total_data"] = len(Y_train)
        current_class_rows = (Y_train == current_class)
        X_train_current = X_train[current_class_rows]
        Y_train_current = Y_train[current_class_rows]
        num_features = X_train.shape[1]
        result[current_class]["total_count"] = len(Y_train_current)
        for j in range(1, num_features + 1):
            result[current_class][j] = {}
            all_possible_values = set(X_train[:, j - 1])
            for current_value in all_possible_values:
                result[current_class][j][current_value] = (X_train_current[:, j - 1] == current_value).sum()
                
    return result

In [ ]:
# Function to find probability of current class
def probability(dictionary, x, current_class):
    output = np.log(dictionary[current_class]["total_count"]) - np.log(dictionary["total_data"])
    num_features = len(dictionary[current_class].keys()) - 1;
    for j in range(1, num_features + 1):
        xj = x[j - 1]
        count_current_class_with_value_xj = dictionary[current_class][j][xj] + 1
        count_current_class = dictionary[current_class]["total_count"] + len(dictionary[current_class][j].keys())
        current_xj_probablity = np.log(count_current_class_with_value_xj) - np.log(count_current_class)           # By taking log values, we prevent multiplication with a 0 probability
        output = output + current_xj_probablity
    return output

In [ ]:
# This function predicts what class a single point belongs to
def predictSinglePoint(dictionary, x):
    classes = dictionary.keys()
    best_p = -1000
    best_class = -1
    first_run = True
    for current_class in classes:
        if (current_class == "total_data"):
            continue
        p_current_class = probability(dictionary, x, current_class)
        if (first_run or p_current_class > best_p):             # Obtaining the class with higher probability
            best_p = p_current_class
            best_class = current_class
        first_run = False
    return best_class

In [ ]:
def predict(dictionary, X_test):
    y_pred = []
    for x in X_test:
        x_class = predictSinglePoint(dictionary, x)
        y_pred.append(x_class)
    return y_pred

In [ ]:
# Converting Iris Data into Labelled data
def makeLabelled(column):
    second_limit = column.mean()
    first_limit = 0.5 * second_limit
    third_limit = 1.5 * second_limit
    for i in range (0,len(column)):
        if (column[i] < first_limit):
            column[i] = 0
        elif (column[i] < second_limit):
            column[i] = 1
        elif(column[i] < third_limit):
            column[i] = 2
        else:
            column[i] = 3
    return column

In [ ]:
# Importing Iris
from sklearn import datasets
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [ ]:
for i in range(0,X.shape[-1]):
    X[:,i] = makeLabelled(X[:,i])

In [ ]:
from sklearn import model_selection
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y,test_size=0.25, random_state=0)

In [ ]:
dictionary = fit(X_train, Y_train)

In [ ]:
Y_pred = predict(dictionary, X_test)

In [ ]:
# Various metrics for understanding how well our model has performed.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Classification Report")
print(classification_report(Y_test, Y_pred))
print("Confusion Matrix")
print(confusion_matrix(Y_test, Y_pred))
print()
print("Accuracy Score")
print(accuracy_score(Y_test, Y_pred) * 100, "%", sep="")

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38

Confusion Matrix
[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]

Accuracy Score
97.36842105263158%


## **Implementation with Continous Data**

For continous data, we need a **probability distribution**. For most of the cases, **Gaussian Distribution** is used.

$$ f(x \; | \; \mu, \sigma^2) = \frac{1}{ \sqrt {2 \pi \sigma^2}} * e^{- \frac{(x - \mu)^2}{2\sigma^2}} $$

where 

$\quad \mu$ is the mean of the distribution

$\quad \sigma$ is the standard deviation, and 

$\quad \mu^2$ is the variance.

Other types of classifiers are **Bernoulli, Multinomial**, etc.

## **Implementation of Naive Bayes using Scikit Learn**

There are three types of Naive Bayes models under the scikit-learn library:

**Gaussian:** It is used in classification and it assumes that features follow a normal distribution.

**Multinomial:** It is used for discrete counts. For example, let’s say,  we have a text classification problem. Here we can consider Bernoulli trials which is one step further and instead of “word occurring in the document”, we have “count how often word occurs in the document”, you can think of it as “number of times outcome number $x_i$ is observed over the n trials”.

**Bernoulli:** The binomial model is useful if your feature vectors are binary (i.e. zeros and ones). One application would be text classification with ‘bag of words’ model where the 1s & 0s are “word occurs in the document” and “word does not occur in the document” respectively.

### **Iris Dataset**

If you remember, for the model we implemented ourselves, we converted our data to labelled data.

For such data, the best model present in Sklearn is **CategoricalNB**. Lets have a look at it.

In [ ]:
from sklearn import naive_bayes
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [ ]:
for i in range(0,X.shape[-1]):
    X[:,i] = makeLabelled(X[:,i])

In [ ]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.25, random_state=0)

In [ ]:
from sklearn.naive_bayes import CategoricalNB
clf = CategoricalNB()
clf.fit(X_train, Y_train)

CategoricalNB(alpha=1.0, class_prior=None, fit_prior=True)

In [ ]:
Y_pred_CategoricalNB = clf.predict(X_test)

In [ ]:
# Various metrics for understanding how well our model has performed.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Classification Report")
print(classification_report(Y_test, Y_pred_CategoricalNB))
print("Confusion Matrix")
print(confusion_matrix(Y_test, Y_pred_CategoricalNB))
print()
print("Accuracy Score")
print(accuracy_score(Y_test, Y_pred_CategoricalNB) * 100, "%", sep="")

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.94      1.00      0.97        16
           2       1.00      0.89      0.94         9

    accuracy                           0.97        38
   macro avg       0.98      0.96      0.97        38
weighted avg       0.98      0.97      0.97        38

Confusion Matrix
[[13  0  0]
 [ 0 16  0]
 [ 0  1  8]]

Accuracy Score
97.36842105263158%


It is observed that our implementation for Categorical data gives us a similar result to sklearn's CategoricalNB.

Now, let's have a look at the **GaussianNB**. Here, we shall use the **original values (continuous)** of the Iris Dataset, instead of using the labelled data we created.

In [ ]:
from sklearn import naive_bayes
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [ ]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.25, random_state=0)

In [ ]:
gnb = naive_bayes.GaussianNB() # GAUSSIAN NAIVE BAYES CLASSIFIER
gnb.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = gnb.predict(X_test)

In [ ]:
# Various metrics for understanding how well the model has performed.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Classification Report")
print(classification_report(Y_test,y_pred))
print("Confusion Matrix")
print(confusion_matrix(Y_test,y_pred))
print()
print("Accuracy Score")
print(accuracy_score(Y_test,y_pred) * 100, "%", sep="")

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00         9

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38

Confusion Matrix
[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]

Accuracy Score
100.0%


Lets take another dataset, **Wine Dataset**

In [ ]:
wine = datasets.load_wine()

In [ ]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = model_selection.train_test_split(wine.data, wine.target, test_size=0.3, random_state=0)

In [ ]:
#Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
y_pred = gnb.predict(X_test)

In [ ]:
print("Classification Report")
print(classification_report(y_test, y_pred))
print("Confusion Matrix")
print(confusion_matrix(y_test, y_pred))
print()
print("Accuracy Score")
print(accuracy_score(y_test, y_pred) * 100, "%", sep="")

Classification Report
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        19
           1       1.00      0.86      0.93        22
           2       0.93      1.00      0.96        13

    accuracy                           0.94        54
   macro avg       0.94      0.95      0.95        54
weighted avg       0.95      0.94      0.94        54

Confusion Matrix
[[19  0  0]
 [ 2 19  1]
 [ 0  0 13]]

Accuracy Score
94.44444444444444%


## **Some Applications**

**Real time Prediction:** Naive Bayes is an eager learning classifier and it is sure fast. Thus, it can be used for making predictions in real time.
Multi class Prediction: This algorithm is also well known for multi class prediction feature. Here we can predict the probability of multiple classes of target variable.

**Text Classification / Spam Filtering / Sentiment Analysis:** Naive Bayes classifiers mostly used in text classification (due to better result in multi class problems and independence rule) have higher success rate as compared to other algorithms. As a result, it is widely used in Spam filtering (identify spam e-mail) and Sentiment Analysis (in social media analysis, to identify positive and negative customer sentiments)

**Recommendation System:** Naive Bayes Classifier and Collaborative Filtering together builds a Recommendation System that uses machine learning and data mining techniques to filter unseen information and predict whether a user would like a given resource or not

## **Tips to improve the power of Naive Bayes Model**

1. If continuous features do not have normal distribution, we should use transformation or different methods to convert it in normal distribution.
2. If test data set has zero frequency issue, apply smoothing techniques “Laplace Correction” to predict the class of test data set.
3. Remove correlated features, as the highly correlated features are voted twice in the model and it can lead to over inflating importance.
4. You might think to apply some classifier combination technique like ensembling, bagging and boosting but these methods would not help. Actually, “ensembling, boosting, bagging” won’t help since their purpose is to reduce variance. Naive Bayes has no variance to minimize.

## **Advantages of Naive Bayes**

1. It is easy and fast to predict class of test data set. It also perform well in multi class prediction
2. When assumption of independence holds, a Naive Bayes classifier performs better compare to other models like logistic regression and you need less training data.
3. It perform well in case of categorical input variables compared to numerical variable(s). For numerical variable, normal distribution is assumed (bell curve, which is a strong assumption).




## **Disadvantages of Naive Bayes**

1. If categorical variable has a category (in test data set), which was not observed in training data set, then model will assign a 0 (zero) probability and will be unable to make a prediction. This is often known as “Zero Frequency”. To solve this, we can use the smoothing technique. One of the simplest smoothing techniques is called Laplace correction.
2. Naive Bayes is also known as a bad estimator, so the probability outputs from predict probability are not to be taken too seriously.
3. Another limitation of Naive Bayes is the assumption of independent predictors. In real life, it is almost impossible that we get a set of predictors which are completely independent.

## **Your Next Step**

We have implemented Naive Bayes for discrete data. We have also seen the implementation of Sklearn to predict continuos data.

Try and write a code to implement Naive Bayes to predict continous data on your own. You may use Gaussian Naive Bayes, or Multinomial Naive Bayes