##### NumPy

**What will you learn?**
1. Introduction to NumPy
2. Advantages
3. **Functionalities of NumPy** : Creation, Manipulation
4. Boolean Indexing
5. NumPy Broadcasting

#####  Introduction

NumPy stands for Numerical Python. It has following features : 

**POWERFUL N-DIMENSIONAL ARRAYS** : Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

**NUMERICAL COMPUTING TOOLS** : NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

**INTEROPERABLE** : NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

**PERFORMANT** : The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

**EASY TO USE** : NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

**OPEN SOURCE** : Distributed under a liberal BSD license, NumPy is developed and maintained publicly on GitHub by a vibrant, responsive, and diverse community.


#####  Advantages over normal lists

You may think, we already have python lists with us to use. So why should we ever opt for NumPy? Let us see some advantages of NumPy over normal python lists.

### **Memory Consumption**

NumPy arrays use much less memory as compared to normal lists. We can easily verify this.

In [ ]:
import numpy as np
import sys

li_arr = [i for i in range(100)]     # Create list of 100 elements
np_arr = np.arange(100)              # Create numpy array of 100 elements

In [ ]:
## Size of 100 elements in numpy array
print(np_arr.itemsize * np_arr.size)

800


In [ ]:
## Size of 100 elements in python list
print(sys.getsizeof(1) * len(li_arr))

2800


### **Time Execution**

NumPy arrays are much faster as compared to python list. We can easily verify this.

In [ ]:
import time
import numpy as np  

In [ ]:
size = 100000

In [ ]:
def addition_using_list():
  t1 = time.time()
  a = range(size)
  b = range(size)
  c = [a[i] + b[i] for i in range(size)]
  t2 = time.time()
  return t2 - t1
  

In [ ]:
def addition_using_numpy():
  t1 = time.time()
  a = np.arange(size)
  b = np.arange(size)
  c = a + b
  t2 = time.time()
  return t2 - t1

In [ ]:
t_list = addition_using_list()
t_numpy = addition_using_numpy()
print("List = ", t_list * 1000)   
print("NumPy = ", t_numpy * 1000)

List =  38.43832015991211
NumPy =  0.5583763122558594


### **Convinient to Use**

It is much easier to perform basic operations in NumPy arrays

## **Why is NumPy Faster Than Lists?**

NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## **Creating NumPy Arrays**

In [ ]:
import numpy as np    ## Use np as an alias for numpy

### **np.array()**

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

**Syntax**

    numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

**Parameters**

1. **object :** array_like

    An array, any object exposing the array interface, an object whose __array__ method returns an array, or any (nested) sequence.

2. **dtype :** data-type, optional

    The desired data-type for the array. If not given, then the type will be determined as the minimum type required to hold the objects in the sequence.

3. **copy :** bool, optional

    If true (default), then the object is copied. Otherwise, a copy will only be made if __array__ returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements (dtype, order, etc.).

In [ ]:
a = [1, 2, 3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a, dtype = str)
print(b)

['1' '2' '3' '5' '4.5']


In [ ]:
a = [1, 2, 3, '5', 4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


### **np.ones()**

**Syntax**

    numpy.ones(shape, dtype=None, order='C', *, like=None)

This function returns a new array of given shape and type, filled with ones.

**Parameters**
1. **shape :** int or sequence of ints

    Shape of the new array, e.g., (2, 3) or 2.

2. **dtype :** data-type, optional

    The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

3. **order :** {‘C’, ‘F’}, optional, default: C

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.
  
4. **like :** array_like

    Reference object to allow the creation of arrays which are not NumPy arrays. If an array-like passed in as like supports the __array_function__ protocol, the result will be defined by it. In this case, it ensures the creation of an array object compatible with that passed in via this argument.

In [ ]:
b = np.ones(3, dtype = int)
b

array([1, 1, 1])

In [ ]:
b = np.ones((2, 3), dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

### **np.zeros()**

**Syntax**

    numpy.zeros(shape, dtype=float, order='C', *, like=None)

This returns a new array of given shape and type, filled with zeros.

**Parameters**
1. **shape :** int or tuple of ints

    Shape of the new array, e.g., (2, 3) or 2.

1. **dtype :** data-type, optional

    The desired data-type for the array, e.g., numpy.int8. Default is numpy.float64.

3. **order :** {‘C’, ‘F’}, optional, default: ‘C’

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.


In [ ]:
b = np.zeros(3, dtype = int)
b

array([0, 0, 0])

In [ ]:
b = np.zeros((3, 4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### **np.full()**

**Syntax**

    numpy.full(shape, fill_value, dtype=None, order='C', *, like=None)

Return a new array of given shape and type, filled with fill_value.

**Parameters**
1. **shape :** int or sequence of ints

    Shape of the new array, e.g., (2, 3) or 2.

2. **fill_value :** scalar or array_like

    Fill value.

3. **dtype :** data-type, optional

    The desired data-type for the array The default, None, means
    np.array(fill_value).dtype.

3. **order :** {‘C’, ‘F’}, optional

    Whether to store multidimensional data in C- or Fortran-contiguous (row- or column-wise) order in memory.



In [ ]:
b = np.full((3, 3), 5, dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

### **np.empty()**

**Syntax**

    numpy.empty(shape, dtype=float, order='C', *, like=None)

This returns a new array of given shape and type, without initializing entries.

**Parameters**
1. **shape :** int or tuple of int

    Shape of the empty array, e.g., (2, 3) or 2.

2. **dtype :** data-type, optional

    Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.

3. **order :** {‘C’, ‘F’}, optional, default: ‘C’

    Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.


In [ ]:
np.empty([2, 2])             # uninitialized

array([[5.e-324, 5.e-324],
       [5.e-324, 0.e+000]])

In [ ]:
np.empty([2, 2], dtype=int)              # uninitialized

array([[           43490272, 6868628531463585792],
       [6854015001108239443, 5572446284745688131]])

**Note:** You will get a different result each time you execute using empty, as the array formed will always be uninitialised.

### **np.arange()**

**Syntax**

    numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

This returns evenly spaced values within a given interval.

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.

**Parameters**
1. **start :** integer or real, optional

    Start of interval. The interval includes this value. The default start value is 0.

2. **stop :** integer or real

    End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

3. **step :** integer or real, optional

    Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

4. **dtype :** dtype

    The type of the output array. If dtype is not given, infer the data type from the other input arguments.

In [ ]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(2, 10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(2, 20, 2)
b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### **np.linspace()**

**Syntax**

    numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)[source]
This returns evenly spaced numbers over a specified interval.


The endpoint of the interval can optionally be excluded.

**Parameters**

1. **start :** array_like
    The starting value of the sequence.

2. **stop :** array_like

    The end value of the sequence, unless endpoint is set to False. In that case, the sequence consists of all but the last of num + 1 evenly spaced samples, so that stop is excluded. Note that the step size changes when endpoint is False.

3. **num :** int, optional

    Number of samples to generate. Default is 50. Must be non-negative.

4. **endpoint :** bool, optional

    If True, stop is the last sample. Otherwise, it is not included. Default is True.

5. **retstep :** bool, optional

    If True, return (samples, step), where step is the spacing between samples.

6. **dtype :** dtype, optional

    The type of the output array. If dtype is not given, the data type is inferred from start and stop. The inferred dtype will never be an integer; float is chosen even if the arguments would produce an array of integers.


7. **axis :** int, optional

    The axis in the result to store the samples. Relevant only if start or stop are array-like. By default (0), the samples will be along a new axis inserted at the beginning. Use -1 to get an axis at the end.



In [ ]:
b = np.linspace(2, 10)
b
print(b[1] - b[0])
print(b[3] - b[2])

0.16326530612244916
0.16326530612244916


In [ ]:
b = np.linspace(2, 10, 5, dtype = int, endpoint = False)
b

array([2, 3, 5, 6, 8])

**The difference between np.arange() and np.linspace() is that, using arange() we actually have control over step value, and using linspace() we have control over the number of values we want to generate.**

### **np.identity()**



**Syntax**

    numpy.identity(n, dtype=None, *, like=None)
This returns the identity array.

The identity array is a **square array** with ones on the main diagonal.

**Parameters**

1. **n :** int
    Number of rows (and columns) in n x n output.

2. **dtype :** data-type, optional
    Data-type of the output. Defaults to float.



In [ ]:
b = np.identity(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **np.eye()**

**Syntax**

    numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

This returns a **2-D array** with ones on the diagonal and zeros elsewhere.

**Parameters**
1. **N :** int

    Number of rows in the output.

1. **M :** int, optional

    Number of columns in the output. If None, defaults to N.

1. **k :** int, optional

    Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

1. **dtype :** data-type, optional

    Data-type of the returned array.

1. **order :** {‘C’, ‘F’}, optional

    Whether the output should be stored in row-major (C-style) or column-major (Fortran-style) order in memory.



In [ ]:
b = np.eye(3, 4)
b

### **np.random.rand()**


**Syntax**

    np.random.rand(d0, d1, ..., dn)

This returns random values in a given shape.

**Parameters**
1. **d0, d1, …, dn :** int, optional

    The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.



In [ ]:
## To generate values in range 0 - 10, we simply multiply by 10
b = np.random.rand(10) * 10    
b

array([6.36252717, 5.46331891, 0.49020069, 1.23093931, 9.64687412,
       8.52428849, 8.59851532, 1.07664848, 0.35596578, 2.98403531])

In [ ]:
b = np.random.rand(2, 3)
b

array([[0.99036289, 0.86868431, 0.83913126],
       [0.99637935, 0.38461734, 0.96949518]])

### **np.random.randint()**

**Syntax**

    random.randint(low, high=None, size=None, dtype=int)

This returns random integers from low (inclusive) to high (exclusive).


**Parameters**
1. **low :** int or array-like of ints

    Lowest (signed) integers to be drawn from the distribution (unless high=None, in which case this parameter is one above the highest such integer).

1. **high :** int or array-like of ints, optional

    If provided, one above the largest (signed) integer to be drawn from the distribution (see above for behavior if high=None). If array-like, must contain integer values

1. **size :** int or tuple of ints, optional

    Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

1. **dtype :** dtype, optional

    Desired dtype of the result. Byteorder must be native. The default value is int.


In [ ]:
np.random.randint(2, size=10)

array([0, 1, 0, 0, 0, 1, 1, 1, 1, 1])

In [ ]:
np.random.randint(1, size=10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.random.randint(5, size=(2, 4))

array([[0, 0, 4, 1],
       [2, 0, 1, 2]])

In [ ]:
np.random.randint(1, [3, 5, 10])

array([1, 4, 6])

## **Indexing and Slicing**

Since we already know how to use indices and perform slicing in normal python lists, we shall see in comparison, how a numpy array does similar things.

### **1-D Arrays**

In [ ]:
import numpy as np

li = [1, 2, 3, 4, 5]
arr = np.array(li)

print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
## Refers to the memory gap between two elements of numpy array
print(arr.strides)  

(5,)
int64
(8,)


In [ ]:
## Accessing elements
print(li[3])
print(arr[3])

4
4


In [ ]:
## Accessing more than one elements
print(li[1:4])
print(arr[1:4])

[2, 3, 4]
[2 3 4]


### **2-D Arrays**

In [ ]:
li_2d = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
arr_2d = np.array(li_2d)

print(li_2d)
print(arr_2d)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int64
(32, 8)


In [ ]:
## Accessing the elements
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2, 1])   # We may use comma also

10
10
10


In [ ]:
## Slicing 
print(li_2d[1][:3])
print(arr_2d[1, :3])

[5, 6, 7]
[5 6 7]


For normal lists, we cannot get elements in column axis. Suppose we want to get elements of 1st, 2nd and 3rd row belonging only to the 2nd column, we may try this: 

In [ ]:
print(li_2d[0:3][2])

But this does not work. Lets break it down into steps

In [ ]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


This is easily possible in numpy arrays : 

In [ ]:
print(arr_2d[0 : 3, 2])

[ 3  7 11]


We may also get multiple sliced rows and columns. Lets see how : 

In [ ]:
print(arr_2d[2:4, 1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


## **Mathematical Operations**

Lets see how numpy arrays simplify mathematical operations for us.

#### **Arithmetic Operations**

In [ ]:
import numpy as np

li = [1, 2, 3, 4, 5]
a = np.random.randint(1, 20, 5)
b = np.random.randint(1, 20, 5)

print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[ 3 19 18  8 19]
[19  3  2  1 17]


In [ ]:
## Adding 1 to each element in list
li = [i+1 for i in li]
li

[2, 3, 4, 5, 6]

In [ ]:
## Adding 1 to each element in numpy array
a = a + 1
a

array([ 4, 20, 19,  9, 20])

In [ ]:
## Adding two numpy arrays
c = a + b
c

array([23, 23, 21, 10, 37])

In [ ]:
## Subtracting two numpy arrays
d = a - b
d

array([-15,  17,  17,   8,   3])

In [ ]:
## Multiplying two numpy arrays
e = a * b
e

array([ 76,  60,  38,   9, 340])

In [ ]:
## Dividing two numpy arrays
f = a / b
f

array([0.21052632, 6.66666667, 9.5       , 9.        , 1.17647059])

In [ ]:
h = a ** b
h

array([        274877906944,                 8000,                  361,
                          9, -8435036407491198976])

In [ ]:
## Some misc operations
print(a)
print(a.sum())    ## Sum of all elements
print(a.mean())   ## Mean of all elements
print(a.min())    ## Minimum of all elements
print(a.argmin()) ## Index of minimum of all elements 
print(a.max())    ## Maximum of all elements
print(a.argmax()) ## Index of maximum of all elements 

[ 4 20 19  9 20]
72
14.4
4
0
20
1


#### **Logical Operations**

In [ ]:
print(a)
print(b)

[ 4 20 19  9 20]
[19  3  2  1 17]


In [ ]:
a > b

array([False,  True,  True,  True,  True])

In [ ]:
a < b

array([ True, False, False, False, False])

In [ ]:
a == b

array([False, False, False, False, False])

In [ ]:
print(np.logical_or(a, b))
print(np.logical_and(a, b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [ ]:
a[2] = 0
print(a)
print(np.logical_not(a))

[ 4 20  0  9 20]
[False False  True False False]


**Try all these operations for 2-D arrays also.**

## **Boolean Indexing**

NumPy also permits the use of a boolean-valued array as an index, to perform advanced indexing on an array. In its simplest form, this is an extremely intuitive and elegant method for selecting contents from an array based on logical conditions.

### **1D Arrays**

Let us see an example

In [ ]:
import numpy as np

In [ ]:
b = np.random.randint(1, 20, 8)
print(b)

[15  6  2 19 12 12  2  5]


In [ ]:
print(b > 10)

[ True False False  True  True  True False False]


In [ ]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[ True False False  True  True  True False False]
[15 19 12 12]


As you see, we are able to extract those elements for which the condition b > 10 was True.

In shorthand, we may do the following :

In [ ]:
new_arr = b[b > 10]
new_arr

array([15, 19, 12, 12])

Some more examples : 

In [ ]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([15, 12, 12])

In [ ]:
print(b)
c = b
c

[15  6  2 19 12 12  2  5]


array([15,  6,  2, 19, 12, 12,  2,  5])

In the next example, we will update some elements on basis of a condition.

In [ ]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[19 19 19 19 12 12  2  5]


array([100, 100, 100, 100,  12,  12,   2,   5])

In [ ]:
print(b)
print(b[b == 100])

[100 100 100 100  12  12   2   5]
[100 100 100 100]


In [ ]:
## To get those indiced where element is 100
ind = np.where(b == 100)
ind

(array([0, 1, 2, 3]),)

### **2D Arrays**

2D arrays work the same as 1D arrays. Lets look at few examples

In [ ]:
import numpy as np
a = np.random.randint(1, 30, (5, 6))
print(a)

[[26  8 22 29 16 23]
 [26 10 15  5  8  8]
 [21 19  2  3 21 23]
 [23  4 25 29 21  2]
 [ 6 26 23 17  5 11]]


In [ ]:
bool_arr = a > 20
print(bool_arr)

[[ True False  True  True False  True]
 [ True False False False False False]
 [ True False False False  True  True]
 [ True False  True  True  True False]
 [False  True  True False False False]]


In [ ]:
ans = a[bool_arr]
print(ans)

[26 22 29 23 26 21 21 23 23 25 29 21 26 23]


In [ ]:
b = a
print(a)

[[26  8 22 29 16 23]
 [26 10 15  5  8  8]
 [21 19  2  3 21 23]
 [23  4 25 29 21  2]
 [ 6 26 23 17  5 11]]


In [ ]:
b[bool_arr] = 100
print(b)

[[100   8 100 100  16 100]
 [100  10  15   5   8   8]
 [100  19   2   3 100 100]
 [100   4 100 100 100   2]
 [  6 100 100  17   5  11]]


We just updated all the values greater than 20 to 100.

In [ ]:
c = np.random.randint(1, 10, (2, 2))
print(c)

[[7 6]
 [1 5]]


In [ ]:
c_bool = np.array([[True, False], [False, True], [True, True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [ ]:
print(c[c_bool])   ## Error generated because dimensions of boolean array and c are not same.

IndexError: ignored

Lets see how we can work over a specific column.

In [ ]:
print(b)

[[100   8 100 100  16 100]
 [100  10  15   5   8   8]
 [100  19   2   3 100 100]
 [100   4 100 100 100   2]
 [  6 100 100  17   5  11]]


In [ ]:
bool_arr = b[:, 3] == 100
print(bool_arr)

[ True False False  True False]


Lets update the array.

In [ ]:
b[bool_arr, 3] = 99
print(b)

[[100   8 100  99  16 100]
 [100  10  15   5   8   8]
 [100  19   2   3 100 100]
 [100   4 100  99 100   2]
 [  6 100 100  17   5  11]]


## **NumPy Broadcasting**

The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes. Broadcasting provides a means of vectorizing array operations so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are, however, cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.


NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:



In [ ]:
import numpy as np

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. The simplest broadcasting example occurs when an array and a scalar value are combined in an operation:

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

The result is equivalent to the previous example where b was an array. We can think of the scalar b being stretched during the arithmetic operation into an array with the same shape as a. The new elements in b are simply copies of the original scalar. The stretching analogy is only conceptual. NumPy is smart enough to use the original scalar value without actually making copies so that broadcasting operations are as memory and computationally efficient as possible.

The code in the second example is more efficient than that in the first because broadcasting moves less memory around during the multiplication (b is a scalar rather than an array).



When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

1. they are equal, or

2. one of them is 1

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the size that is not 1 along each axis of the inputs.

In [ ]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3, 3))
print(x)
print(y)

[[7 3 6]
 [9 6 3]
 [3 1 8]]
[[4 3 9]
 [3 4 9]
 [6 7 1]]


In [ ]:
ans = x - y
print(ans)

[[ 3  0 -3]
 [ 6  2 -6]
 [-3 -6  7]]


In [ ]:
x = np.random.randint(1, 10, (3, 3))
y = np.random.randint(1, 10, (3))
print(x)
print(y)

[[3 4 1]
 [6 5 5]
 [1 4 1]]
[6 1 4]


In [ ]:
ans = x - y
print(ans)

[[-3  3 -3]
 [ 0  4  1]
 [-5  3 -3]]


In [ ]:
x = np.random.randint(1, 10, (3, 2))
y = np.random.randint(1, 10, (2, 3))
print(x)
print(y)

[[1 1]
 [6 1]
 [3 3]]
[[6 3 4]
 [1 1 2]]


#### **Transpose**

To make these two arrays compatible, we may **transpose** one array.

In [ ]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[6 1]
 [3 1]
 [4 2]]
[[-5  0]
 [ 3  0]
 [-1  1]]


#### **Reshape**

We may also **reshape** our array. Lets see an example : 

In [ ]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
y = np.random.randint(1, 10, (4, 4))
y

array([[7, 2, 6, 8],
       [3, 4, 6, 3],
       [2, 7, 9, 7],
       [2, 3, 4, 8]])

In [ ]:
x * y    ## Error generated

ValueError: ignored

Lets reshape 'x'

In [ ]:
x = np.reshape(x, (4, 4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Now we may multiply, subtract, add or divide 'x' and 'y'.

In [ ]:
x * y

array([[  0,   2,  12,  24],
       [ 12,  20,  36,  21],
       [ 16,  63,  90,  77],
       [ 24,  39,  56, 120]])

In [ ]:
x - y

array([[-7, -1, -4, -5],
       [ 1,  1,  0,  4],
       [ 6,  2,  1,  4],
       [10, 10, 10,  7]])

In [ ]:
x + y

array([[ 7,  3,  8, 11],
       [ 7,  9, 12, 10],
       [10, 16, 19, 18],
       [14, 16, 18, 23]])

In [ ]:
x / y

array([[0.        , 0.5       , 0.33333333, 0.375     ],
       [1.33333333, 1.25      , 1.        , 2.33333333],
       [4.        , 1.28571429, 1.11111111, 1.57142857],
       [6.        , 4.33333333, 3.5       , 1.875     ]])

In [ ]:
x // y 

array([[0, 0, 0, 0],
       [1, 1, 1, 2],
       [4, 1, 1, 1],
       [6, 4, 3, 1]])

In [ ]:
x % y

array([[0, 1, 2, 3],
       [1, 1, 0, 1],
       [0, 2, 1, 4],
       [0, 1, 2, 7]])