# **Feature Scaling**

**Feature scaling** is the technique to bring all the features to the same scale. If we don’t bring the features to the same scale, the model tends to give higher weightage to higher values and lower weightage to lower values irrespective of the units of values. 
Feature scaling is bringing continuous variables to the same scale. 

For example, student A got 60 out of 100 in subject 1, 120 out of 150 in subject 2, 180 out of 200 in subject 3.

After rescaling to 10, Student A got 6 out of 10 in subject 1, 8 out of 10 in subject 2, 9 out of 10 in subject 3


## **Why Feature Scaling?**

Machine learning algorithms like linear regression, logistic regression, neural network, etc. that use gradient descent as an optimization technique require data to be scaled. The difference in ranges of features will cause different step sizes for each feature. To ensure that the gradient descent moves smoothly towards the minima and that the steps for gradient descent are updated at the same rate for all the features, we scale the data before feeding it to the model.

There are two types of feature scaling used in Machine learning 

1. Min-Max normalization
2. Standardization.

### **Min-Max Normalization**

It is a scaling technique in which values are shifted and rescaled so that they end up ranging between 0 and 1.
$$ X_{new} =  \frac{(X_i-X_{min})}{X_{max} -X_{min}}$$

Here, $X_{max}$ and $X_{min}$ are the maximum and the minimum values of the feature respectively.

When the value of $X_i$ is the minimum value , the numerator will be 0, and hence $X_{new}$ is 0 . On the other hand, when the value of $X_i$ is the maximum value , the numerator is equal to the denominator and thus the value of $X_{new}$ is 1
If the value of X is between the minimum and the maximum value, then the value of $X_{new}$ is between 0 and 1

**Min-Max Normalization Using Sklearn**

In Sklearn Preprocessing module , the function for doing Min_max normalization is MinMaxScaler. 

$$  sklearn.preprocessing.MinMaxScaler(feature__range=0, 1, *, copy=True, clip=False)$$

**Parameters**

**feature_range**: tuple (min, max), default=(0, 1)
Desired range of transformed data.

**copy**: bool, default=True
Set to False to perform inplace row normalization and avoid a copy (if the input is already a numpy array).

**clip**: bool, default=False
Set to True to clip transformed values of held-out data to provided feature range

### **Standardization**

It is another scaling technique where the values are centered around the mean with a unit standard deviation. This means that the mean of the attribute becomes zero and the resultant distribution has a unit standard deviation.
$$X_{new}=\frac{x_i-X_{mean}}{u}$$

where u is the standard deviation of the feature values

**Standardization using Sklearn**

In Sklearn, the function for standardization is

$$sklearn.preprocessing.StandardScaler(*, copy=True, with__mean=True, with__std=True)$$

The Standard Scaler assumes data is normally distributed within each feature and scales them such that the distribution centered around 0, with a standard deviation of 1.


The standard score of a sample x is calculated as:

$$z = (x - u) / s$$

where u is the mean of the training samples or zero if with _ mean=False, and s is the standard deviation of the training samples or one if with _std=False.

**Parameters**

**copy**: bool, default=True
If False, try to avoid a copy and do inplace scaling instead. This is not guaranteed to always work inplace; e.g. if the data is not a NumPy array or scipy.sparse CSR matrix, a copy may still be returned.

**with_mean**:bool, default=True
If True, center the data before scaling. This does not work (and will raise an exception) when attempted on sparse matrices, because centering them entails building a dense matrix which in common use cases is likely to be too large to fit in memory.

**with_std**:bool, default=True
If True, scale the data to unit variance (or equivalently, unit standard deviation).

## **Implementing Feature Scaling using Sklearn**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn import datasets
wine = datasets.load_wine()

In [ ]:
columnNames = ['Alcohol' , 'Malic acid' , 'Ash' , 'Alcalinity of ash' , 'Magnesium' ,'Total phenols' , 'Flavanoids','Nonflavanoid phenols' ,'Proanthocyanins','Color intensity' ,'Hue' ,'OD280/OD315 of diluted wines' ,'Proline'     ]

In [ ]:
X = wine.data
X

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [ ]:
wine_df = pd.DataFrame(X, columns = columnNames)
wine_df.head()

Alcohol  Malic acid   Ash  ...   Hue  OD280/OD315 of diluted wines  Proline
0    14.23        1.71  2.43  ...  1.04                          3.92   1065.0
1    13.20        1.78  2.14  ...  1.05                          3.40   1050.0
2    13.16        2.36  2.67  ...  1.03                          3.17   1185.0
3    14.37        1.95  2.50  ...  0.86                          3.45   1480.0
4    13.24        2.59  2.87  ...  1.04                          2.93    735.0

[5 rows x 13 columns]

The wine dataset is a very simple classification dataset. There are 3 types pf wines, (0, 1, 2) and we have 13 features on basis of which they are classified. You may view the names of features by


In [ ]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [ ]:
from sklearn import preprocessing
wine_scaled = preprocessing.scale(X)
wine_scaled

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [ ]:
# Returns numpy array , so we converted it back to dataframe 
wine_scaled_df = pd.DataFrame(wine_scaled , columns = columnNames)
wine_scaled_df.head()

Alcohol  Malic acid  ...  OD280/OD315 of diluted wines   Proline
0  1.518613   -0.562250  ...                      1.847920  1.013009
1  0.246290   -0.499413  ...                      1.113449  0.965242
2  0.196879    0.021231  ...                      0.788587  1.395148
3  1.691550   -0.346811  ...                      1.184071  2.334574
4  0.295700    0.227694  ...                      0.449601 -0.037874

[5 rows x 13 columns]

This is the simplest scaler present in sklearn. This scales our data in such a way that the mean of the entire data is 0, and standard deviation becomes 1

In [ ]:
wine_scaled.std(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

The problem with this method is that, we have to combine both testing and training data to perform the scale. This will bias the model evaluation because information would have leaked from the test set to the training set.

Also, if we receive new training points in future, they will be scaled according to their own features, irrespective of the value of old data. This will lead to huge problems in your ML model. We need some way to store the method with which scaling was done.

Thus, we usually do not use this.

**Min-Max Scaler**

Normalization requires that you know or are able to accurately estimate the minimum and maximum observable values. 
Transform features by scaling each feature to a given range.

Min-Max Scaler estimator scales and translates each feature individually such that it is in the given range on the training set, e.g. between zero and one.

In [ ]:
min_max_scaler_object = preprocessing.MinMaxScaler()

In [ ]:
min_max_scaler_object.fit(X)
wine_min_max = min_max_scaler_object.transform(X)
wine_min_max

array([[0.84210526, 0.1916996 , 0.57219251, ..., 0.45528455, 0.97069597,
        0.56134094],
       [0.57105263, 0.2055336 , 0.4171123 , ..., 0.46341463, 0.78021978,
        0.55064194],
       [0.56052632, 0.3201581 , 0.70053476, ..., 0.44715447, 0.6959707 ,
        0.64693295],
       ...,
       [0.58947368, 0.69960474, 0.48128342, ..., 0.08943089, 0.10622711,
        0.39728959],
       [0.56315789, 0.36561265, 0.54010695, ..., 0.09756098, 0.12820513,
        0.40085592],
       [0.81578947, 0.66403162, 0.73796791, ..., 0.10569106, 0.12087912,
        0.20114123]])

In [ ]:
wine1 = pd.DataFrame(wine_min_max , columns = columnNames)

In [ ]:
wine1.head()

Alcohol  Malic acid  ...  OD280/OD315 of diluted wines   Proline
0  0.842105    0.191700  ...                      0.970696  0.561341
1  0.571053    0.205534  ...                      0.780220  0.550642
2  0.560526    0.320158  ...                      0.695971  0.646933
3  0.878947    0.239130  ...                      0.798535  0.857347
4  0.581579    0.365613  ...                      0.608059  0.325963

[5 rows x 13 columns]

You now may use the same object, to transform any data in the similar manner.

### **Standard Scaler**

StandardScaler follows Standard Normal Distribution (SND). 

 standardize features by removing the mean and scaling to unit variance. 



In [ ]:
standard_scaler_object = preprocessing.StandardScaler()

In [ ]:
standard_scaler_object.fit(X)
wine_standard = standard_scaler_object.transform(X)
wine_standard

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])

In [ ]:
wine2 = pd.DataFrame(wine_standard , columns = columnNames)

In [ ]:
wine2.head()

Alcohol  Malic acid  ...  OD280/OD315 of diluted wines   Proline
0  1.518613   -0.562250  ...                      1.847920  1.013009
1  0.246290   -0.499413  ...                      1.113449  0.965242
2  0.196879    0.021231  ...                      0.788587  1.395148
3  1.691550   -0.346811  ...                      1.184071  2.334574
4  0.295700    0.227694  ...                      0.449601 -0.037874

[5 rows x 13 columns]

In [ ]:
wine_standard.std(axis = 0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Most of the times, we implement the standard scalar.**


However both Standard Scalar and Min Max Scaler are sensitive to outliers.
There is another scaler, the Robust Scaler, which gives better results when data has outliers.

### **Robust Scaler**

Robust Scaler scales features using statistics that are robust to outliers.

This Scaler removes the median and scales the data according to the quantile range (defaults to IQR: Interquartile Range). The IQR is the range between the 1st quartile (25th quantile) and the 3rd quartile (75th quantile).

Centering and scaling happen independently on each feature by computing the relevant statistics on the samples in the training set. Median and interquartile range are then stored to be used on later data using the transform method.

Standardization of a dataset is a common requirement for many machine learning estimators. Typically this is done by removing the mean and scaling to unit variance. However, outliers can often influence the sample mean / variance in a negative way. In such cases, the median and the interquartile range often give better results.

In [ ]:
from sklearn.preprocessing import RobustScaler
X = [[ 1., -2.,  2.],
     [ -2.,  1.,  3.],
     [ 4.,  1., -2.]]
transformer = RobustScaler().fit(X)
transformer.transform(X)

array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

**There are some more scalers to look at other than already covered.**

### **Your Next Task**

You may look into other scalers, such as MaxAbsScaler, QuantileTransformer and Normaliser. Refer to the link below

https://scikit-learn.org/stable/modules/classes.html#module-sklearn.preprocessing
